### ISSUE TITLE
Are the results of join not guaranteed to be correct?

### ISSUE THREAD

**Issue by Cerdore** [psiul/ICDE2019-GPU-Join#7]
Hi!

For example, there is a tuple of results after a join: 
```
key  | value | key  | value 
-----+-------+------+-------
  5  |  953  |   5  |  40
```

But in the code `'join_partitioned_results'`, it just materializes the result without considering whether the two values are adjacent to each other in the output. That is, the two values 40 and 953 are not adjacent to each other.

```
    if (lid < shuffle_ptr) {
        output[ptr + lid] = warp_shuffle[lid]; // warp_shuffle[lid] is the first value
        output[ptr + lid + shuffle_ptr] = warp_shuffle[lid + SHUFFLE_SIZE]; // it's the second value
    }
```
If `shuffle_ptr != 1`, we can't get the two values that are adjacent to each other. Am I right?

Looking forward to your reply!

**Comment by psiul** [comment]
Hi cerdore,

The payloads are not adjacent to each other as they would be in a row-store.
The data layout is PAX-like (16 payloads from probe, then 16 from build).
This is not a matter of correctness but of access patterns.

Best,
Panos

**Comment by Cerdore** [comment]
Hi psiul,

Thank you for your detailed elaboration! Sorry for my ignorance.

But the **k** (size of this vertical partition) is indeterminate, right? For example, the **k** of the following images are all of size 3. It looks like the size of the vertical partition in your code is determined by `shffle_ptr`.
So I'm having some difficulty accessing `output` in row-format on the CPU side... In fact, I was going to add an attribute key. Do you have any suggestions? 
 
![image](https://user-images.githubusercontent.com/24353799/140714088-d5cfa393-e144-4562-8832-457411ec1fbb.png)

Thank you in advance.

Best,
Xiansen

**Comment by Cerdore** [comment]
Thanks, I've solved my problem.

Best,
Xiansen
